import os

# Where we save logs
logs_path = os.getcwd() + "/log/"

default_room = {
    "n_type": 3,
    "x0": 1,
    "x1": 1,
    "x2": 1,
    "t_max": 20,
    "tutorial_t_max": 5
}

pseudos = [
    'Arthur',
    'Agrève',
    'Anselin',
    'Authaire',
    'Avold',
    'Barral',
    'Bérard',
    'Caribert',
    'Centule',
    'Childebert',
    'Clodomir',
    'Clotaire',
    'Conan',
    'Drogon',
    'Durand',
    'Flocel',
    'Flodoard',
    'Flouard',
    'Flour',
    'Floxel',
    'Folquet',
    'Fortunat',
    'Foulque',
    'Frajou',
    'Frambault',
    'Frambourg',
    'Frameric',
    'Francaire',
    'Fulbert',
    'Gaillon',
    'Gaubert',
    'Guéthenoc',
    'Guibin',
    'Guiscard',
    'Hatton',
    'Haynhard',
    'Héribert',
    'Herlemond',
    'Hoel',
    'Honfroi',
    'Hugon',
    'Isembert',
    'Jacquemin',
    'Jacut',
    'Lagier',
    'Lancelot',
    'Lancelin',
    'Lothaire',
    'Mesmin',
    'Milon',
    'Odo',
    'Perceval',
    'Sicard',
    'Sifard',
    'Sigebert',
    'Taillefer',
    'Vantelme'
]

